<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Forms\**" />
    <EmbeddedResource Remove="Forms\**" />
    <None Remove="Forms\**" />
    <Page Remove="Forms\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Modules\Activities\FocusForge.Activities.UI\FocusForge.Activities.UI.csproj" />
    <ProjectReference Include="..\..\Modules\PomodoroTimer\FocusForge.PomodoroTimer.UI\FocusForge.PomodoroTimer.UI.csproj" />
    <ProjectReference Include="..\..\Modules\TimeTracker\FocusForge.TimeTracker.UI\FocusForge.TimeTracker.UI.csproj" />
    <ProjectReference Include="..\..\Shared\FocusForge.Shared.DataModels\FocusForge.Shared.DataModels.csproj" />
    <ProjectReference Include="..\..\Shared\FocusForge.Shared.UI\FocusForge.Shared.UI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.5.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.4">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
</Project>