// <auto-generated />
using FocusForge.PomodoroTimer.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FocusForge.PomodoroTimer.DAL.Migrations
{
    [DbContext(typeof(WachmanDbContext))]
    [Migration("20250916181342_AddTimeCampIntegrationData")]
    partial class AddTimeCampIntegrationData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("FocusForge.Shared.DataModels.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsValue")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SettingsKey = "WorkSessionDuration",
                            SettingsValue = "30"
                        },
                        new
                        {
                            Id = 2,
                            SettingsKey = "BreakTimeDuration",
                            SettingsValue = "5"
                        },
                        new
                        {
                            Id = 3,
                            SettingsKey = "DisableBreaks",
                            SettingsValue = "0"
                        },
                        new
                        {
                            Id = 4,
                            SettingsKey = "ApiKey",
                            SettingsValue = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
