// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wachman.DAL;

#nullable disable

namespace Wachman.DAL.Migrations
{
    [DbContext(typeof(WachmanDbContext))]
    partial class WachmanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Wachman.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SettingsKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsValue")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SettingsKey = "WorkSessionDuration",
                            SettingsValue = "30"
                        },
                        new
                        {
                            Id = 2,
                            SettingsKey = "BreakTimeDuration",
                            SettingsValue = "5"
                        },
                        new
                        {
                            Id = 3,
                            SettingsKey = "DisableBreaks",
                            SettingsValue = "0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
