@apiBaseAddress = https://app.timecamp.com/third_party/api

GET {{apiBaseAddress}}/entries?
&from=2022-05-26
&to=2022-05-26 HTTP/1.1
Authorization: Bearer {{apiKey}}
Accept: application/json
###
GET {{apiBaseAddress}}/timer_running
Authorization: Bearer {{apiKey}}
Accept: application/json
###
Post {{apiBaseAddress}}/timer
Authorization: Bearer {{apiKey}}
Accept: application/json

{
  "action": "status"
}
###