<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Fonts\digital-7 (mono).ttf" />
    <None Remove="Fonts\digital-7.ttf" />
    <None Remove="Images\FocusForgeLogo.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.4" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.DotNet.UpgradeAssistant.Extensions.Default.Analyzers" Version="0.4.421302">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="9.0.4" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Fonts\digital-7 (mono).ttf" />
    <Resource Include="Fonts\digital-7.ttf" />
    <Resource Include="Images\FocusForgeLogo.png" />
  </ItemGroup>
</Project>