<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.4" />
    <PackageReference Include="RestSharp" Version="112.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\FocusForge.Shared.Abstractions\FocusForge.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Shared\FocusForge.Shared.DataModels\FocusForge.Shared.DataModels.csproj" />
    <ProjectReference Include="..\..\TimeTracker\FocusForge.TimeTracker.Messages\FocusForge.TimeTracker.Messages.csproj" />
  </ItemGroup>

</Project>
